---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: site
          image: gcr.io/runa-dev/ui
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcloud
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: ui.logv.app
      http:
        paths:
          - path: /
            backend:
              serviceName: ui
              servicePort: 80
