[package]
name = "logv"
version = "0.0.4"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# auth={path="../auth"}
glob= "0.3.0"
anyhow= "1.0.28"
env_logger= "0.7.1"
futures = { version = "^0.3.4", features = ["thread-pool"] }
serde={ version = "^1.0.106", features = ["derive", "rc"] }
serde_yaml= "^0.8.11"
serde_urlencoded= "^0.6.1"
serde_json={ version = "^1.0.51", features = ["preserve_order"] }
url= "^2.1.1"
chrono={ version = "^0.4.11", features = ["serde"] }
colored_json= "^2.1.0"
http= "^0.2.1"
base64="^0.12.0"
sled="^0.32.0"
bincode= "^1.2.1"
tokio={ version = "^0.2.18", features = ["blocking", "rt-threaded", "io-std", "stream", "sync", "macros", "net"] }
uuid={ version = "^0.8.1", features = ["serde", "v4"] }
webbrowser= "^0.5.2"
directories= "^2.0.2"
ansi_term= "^0.12.1"
atty= "^0.2.14"
clap={version="3.0.0-beta.1"}
open = "^1.4.0"
thiserror= "^1.0.15"
async-std={ version = "^1.5.0", features = ["unstable"] }
tokio-tungstenite="*" 
tungstenite= "^0.10.1"
globset= "^0.4.5"

[features]
default = []
