name: Windows Binary Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  binary:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          .\vcpkg install openssl:x64-windows-static
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static
        with:
          command: build
          args: --release --all-features --manifest-path "packages/logv/logv.cli/Cargo.toml"
      - name: Install AWS CLI
        run: |
          curl "https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi" -o "C:\AWSCLI64PY3.msi"
          msiexec.exe /qn /i "C:\AWSCLI64PY3.msi"
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          ls -1la target
          ls -1la target/release
          cd ./target/release
          tar -czvf logv.tar.gz ./logv.exe
          aws s3 cp --acl public-read --follow-symlinks ./logv.tar.gz s3://logv.app/releases/$RELEASE_VERSION/x86_64-pc-windows-msvc/logv.tar.gz
          aws s3 cp --acl public-read --follow-symlinks ./logv.exe s3://logv.app/releases/$RELEASE_VERSION/x86_64-pc-windows-msvc/logv.exe
